"""MAVLink communication layer — connection, heartbeat, telemetry parsing.

All pymavlink imports are confined to this package (RL-04).
"""

from striker.comms.connection import ConnectionState, MAVLinkConnection
from striker.comms.heartbeat import HeartbeatMonitor
from striker.comms.messages import (
    ATTITUDE,
    COMMAND_ACK,
    GLOBAL_POSITION_INT,
    HEARTBEAT,
    MAV_AUTOPILOT_INVALID,
    MAV_CMD_COMPONENT_ARM_DISARM,
    MAV_CMD_DO_CHANGE_SPEED,
    MAV_CMD_DO_LAND_START,
    MAV_CMD_DO_SET_MODE,
    MAV_CMD_DO_SET_SERVO,
    MAV_CMD_MISSION_SET_CURRENT,
    MAV_CMD_SET_MESSAGE_INTERVAL,
    MAV_CMD_NAV_LAND,
    MAV_CMD_NAV_TAKEOFF,
    MAV_CMD_NAV_WAYPOINT,
    MAV_FRAME_GLOBAL_RELATIVE_ALT,
    MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,
    MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
    MAV_MODE_FLAG_SAFETY_ARMED,
    MAV_RESULT_ACCEPTED,
    MAV_TYPE_GCS,
    MAVLINK_MSG_ID_MISSION_CURRENT,
    MAVLINK_MSG_ID_MISSION_ITEM_REACHED,
    MISSION_ACK,
    MISSION_COUNT,
    MISSION_CURRENT,
    MISSION_ITEM_REACHED,
    MISSION_REQUEST,
    MISSION_REQUEST_INT,
    STATUSTEXT,
    SYS_STATUS,
    VFR_HUD,
    WIND,
    build_heartbeat_msg,
    send_command_long,
    wait_for_command_ack,
    wait_for_message,
)
from striker.comms.telemetry import (
    AttitudeData,
    BatteryData,
    GeoPosition,
    SpeedData,
    SystemStatus,
    TelemetryParser,
    WindData,
)

__all__ = [
    # Messages
    "ATTITUDE",
    "COMMAND_ACK",
    "GLOBAL_POSITION_INT",
    "HEARTBEAT",
    # MAVLink constants
    "MAV_AUTOPILOT_INVALID",
    "MAV_CMD_COMPONENT_ARM_DISARM",
    "MAV_CMD_DO_CHANGE_SPEED",
    "MAV_CMD_DO_LAND_START",
    "MAV_CMD_DO_SET_MODE",
    "MAV_CMD_DO_SET_SERVO",
    "MAV_CMD_MISSION_SET_CURRENT",
    "MAV_CMD_SET_MESSAGE_INTERVAL",
    "MAV_CMD_NAV_LAND",
    "MAV_CMD_NAV_TAKEOFF",
    "MAV_CMD_NAV_WAYPOINT",
    "MAV_FRAME_GLOBAL_RELATIVE_ALT",
    "MAV_FRAME_GLOBAL_RELATIVE_ALT_INT",
    "MAV_MODE_FLAG_CUSTOM_MODE_ENABLED",
    "MAV_MODE_FLAG_SAFETY_ARMED",
    "MAV_RESULT_ACCEPTED",
    "MAV_TYPE_GCS",
    "MAVLINK_MSG_ID_MISSION_CURRENT",
    "MAVLINK_MSG_ID_MISSION_ITEM_REACHED",
    "MISSION_ACK",
    "MISSION_COUNT",
    "MISSION_CURRENT",
    "MISSION_ITEM_REACHED",
    "MISSION_REQUEST",
    "MISSION_REQUEST_INT",
    "STATUSTEXT",
    "SYS_STATUS",
    "VFR_HUD",
    "WIND",
    # Telemetry
    "AttitudeData",
    "BatteryData",
    # Connection
    "ConnectionState",
    "GeoPosition",
    # Heartbeat
    "HeartbeatMonitor",
    "MAVLinkConnection",
    "SpeedData",
    "SystemStatus",
    "TelemetryParser",
    "WindData",
    "build_heartbeat_msg",
    "send_command_long",
    "wait_for_command_ack",
    "wait_for_message",
]
